version: 2

jobs:
  test_8.0:
    working_directory: ~/laravel-crud
    docker:
      - image: circleci/php:8.0-fpm-node-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y python3 python3-pip
            pip3 install coverage coveralls
      - run: sudo composer self-update --no-progress --no-interaction
      - run: composer install --no-progress --no-interaction --prefer-dist
      - run: ./vendor/bin/phpunit
      - run:
          name: Generate code coverage report
          command: coverage run -m unittest discover
      - run:
          name: Upload code coverage report to Coveralls
          command: coveralls
          environment:
            COVERALLS_REPO_TOKEN: oTgNlNs5fUmP2vsiEDuCET4o1RCyC7iBe
workflows:
  version: 2
  test:
    jobs:
      - test_8.0
